apiVersion: v1
kind: Secret
metadata:
  name: app-db-secret
  namespace: app
type: Opaque
stringData:
  POSTGRES_USER: "pguser"        # will match postgres-secret; you can create this from postgres-secret later
  POSTGRES_PASSWORD: "pgpassword"
